### ISSUE TITLE
Crash on win

### ISSUE THREAD

**Issue by lithorse** [otto-r/Lab4#34]
Krashar efter jag trycker på enter efter att ha vunnit. 

![](https://i.imgur.com/W5ezzKP.png)

Ser ut som att den inte hittar HighScore.txt

@otto-r

**Comment by otto-r** [comment]
Okej, trodde den skapade en txt fil automatiskt tydligen inte. Får fixa det sedan.
En fix är ju att skapa "HighScore.txt" i debug mappen så länge.

**Comment by lithorse** [comment]
Funkade att lägga i debug mappen. Slog stalins score

**Comment by otto-r** [comment]
haha, vad bra :)

**Comment by otto-r** [comment]
Fixed by merging of the branch "Update"
